name: Test

on:
  push:
    branches:
      - test
jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
  changes:
    needs: checkout
    runs-on: ubuntu-latest
    steps:
      - run: ls -al
